config/routes.rb
Rails.application.routes.draw do
  resources :types
  resources :foods

  match '/mealplanner', :to => "dashboard#show", :via => [:get]

  get 'updatefood', to: 'foods#update_all'
  get 'api/food/', to: 'foods#get_food_json'

  root to: redirect("/mealplanner")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  has_one :type
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :food
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  require 'rest-client'
  # GET /foods
  # GET /foods.json
  def index
    if params[:type]
      type_id = (Type.where('name = ?', params[:type]))[0][:id]
      @foods  = Food.where('type_id = ?', type_id)
    else
      @foods = Food.all
    end
  end

  def get_food_json
    if params[:type]
      type_id = (Type.where('name = ?', params[:type]))[0][:id]
      foods  = Food.where('type_id = ?', type_id)
    else
      foods = Food.all
    end
    render json: foods, status: :ok
  end

  def update_all
    url = 'https://foodvisor.io/itw/food/list/'
    foodRaw = RestClient.get(url, {:params => {:foo => 'bar'}, :Authorization => 'Bearer iwn-31@!3pf(w]pmarewj236^in'})
    foods = JSON.parse(foodRaw)
    Food.destroy_all
    if is_type_table_empty
      init_types
    end
    p foods
    foods.each do |food|
      food["type_id"] = Type.where(:name => food["type"])[0].id
      food["name"] = food["display_name"]
      food.delete("display_name")
      food.delete("type")
      Food.new(food).save
    end
    foods = Type.all.includes(:food)
    foods.each do |food|
      p food
    end
    render json: foods, status: :ok
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  def is_type_table_empty
    return Type.first == nil
  end

  def init_types
    Type.new({:id => 0, :name => 'starter'}).save
    Type.new({:id => 1, :name => 'dish'}).save
    Type.new({:id => 2, :name => 'desert'}).save
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    def food_params
      params.require(:food).permit(:name, :carbs, :fibers, :proteins, :lipids, :cal, :imgUrl, :type_id)
    end

end

app/controllers/meal_planner_controller.rb
class MealPlannerController < ApplicationController
  max_calories = 500
  
  def find_meals
    max_calories = 500
    meals = []
    starters = select_foods_with_calories_under(max_calories, 1)
    meals = embedd_each_inside_array(sarters)

  end

  private
  def add_dish_type_to_meal(max_calories, meals, dish_type)
    next_dish = select_foods_with_calories_under(max_calories - lowest_cal_meal(meals)[:cal], dish_type)

  end
  def lowest_cal_meal(meals)
    return meals.min {|a,b| a[:cal] <=> b[:cal] }
  end
  def dump_largest_meals(meals, max_calories)
    meals.each do |meal|
      if meal_is_more_cals_than(meal, max_calories)
        meals.delete(meal)
      end
    end
  end
  def embedd_each_inside_array(array)
    return array.collect {|element| {cal: element.cal, first_dish: Array(element)} }
  end
  def select_foods_with_calories_under(calorie, foodtype)
    food = Food.all.select(:name, :cal).where("type_id = ? ", foodtype).where("cal < ? ", calorie)
    return food.to_a
  end
  def meal_is_more_cals_than(meal, max_calories)
    total = 0
    meal.each do |dish|
      total = total + dish.cal
    end
    return total < calorie
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/show.html.erb
<body ui-view></body>

app/views/foods/_form.html.erb
<%= form_with(model: food, local: true) do |form| %>
  <% if food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :carbs %>
    <%= form.text_field :carbs %>
  </div>

  <div class="field">
    <%= form.label :fibers %>
    <%= form.text_field :fibers %>
  </div>

  <div class="field">
    <%= form.label :proteins %>
    <%= form.text_field :proteins %>
  </div>

  <div class="field">
    <%= form.label :lipids %>
    <%= form.text_field :lipids %>
  </div>

  <div class="field">
    <%= form.label :cal %>
    <%= form.text_field :cal %>
  </div>

  <div class="field">
    <%= form.label :imgUrl %>
    <%= form.text_field :imgUrl %>
  </div>

  <div class="field">
    <%= form.label :types_id %>
    <%= form.text_field :types_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Foods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Carbs</th>
      <th>Fibers</th>
      <th>Proteins</th>
      <th>Lipids</th>
      <th>Cal</th>
      <th>Imgurl</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.carbs %></td>
        <td><%= food.fibers %></td>
        <td><%= food.proteins %></td>
        <td><%= food.lipids %></td>
        <td><%= food.cal %></td>
        <td><%= food.imgUrl %></td>
        <td><%= food.type_id %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food.name %>
</p>

<p>
  <strong>Carbs:</strong>
  <%= @food.carbs %>
</p>

<p>
  <strong>Fibers:</strong>
  <%= @food.fibers %>
</p>

<p>
  <strong>Proteins:</strong>
  <%= @food.proteins %>
</p>

<p>
  <strong>Lipids:</strong>
  <%= @food.lipids %>
</p>

<p>
  <strong>Cal:</strong>
  <%= @food.cal %>
</p>

<p>
  <strong>Imgurl:</strong>
  <%= @food.imgUrl %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="foodapp" ng-strict-di>
  <head>
    <title>FOOOOOD</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.png') %>

  </head>
  <div class="head">
    <div class=column">
      <button type="button" ng-click="updateData()">Update food from API</button>
    </div>
    <div class=column">
      <a type="button" href="http://localhost:3000/foods">Browse food DB</a>
    </div>
    <div class=column">
      <a type="button" href="http://0.0.0.0:3000/">Meals</a>
    </div>
    <div class=column">
      <a href="http://localhost:3000/types">Browse types DB</a>
    </div>
  </div>

    <%= yield %>

</html>

app/views/types/_form.html.erb
<%= form_with(model: type, local: true) do |form| %>
  <% if type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= type.name %></td>
        <td><%= link_to 'Show', type %></td>
        <td><%= link_to 'Edit', edit_type_path(type) %></td>
        <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<h1>New Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @type.name %>
</p>

<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>